### ISSUE TITLE
Incorrect info.plist

### ISSUE THREAD

**Issue by MarcoImoo** [neosurance/NeosuranceSDK_v3_ios#1]
The info.plist described in the Readme and used in the example app is incorrect: if you use 'processing' for UIBackgroundModes, you have to insert a list of identifiers used to submit, otherwise the app gets rejected. 
Below the error returned:

> ERROR ITMS-90771: "Missing Info.plist value. The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'. For more information, refer to the Information Property List Key Reference at https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html."

**Comment by neosurance** [comment]
the processing  UIBackgroundModes is unnecessary, removed from doc
